- hosts: ubuntu
  become: yes
  tasks:
    - name: instalar apache2
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: asegurarse de que apache2 está activo
      service:
        name: apache2
        state: started
        enabled: yes

    - name: instalar paquetes random
      apt:
        name:
          - htop
          - figlet
          - net-tools
        state: present
