---
- name: Configurar máquina víctima
  hosts: victima
  become: true

  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Instalaremos apache
      apt:
        name: apache2
        state: present

    - name: Nos aseguramos de que este encendido apache
      service:
        name: apache2
        state: started
        enabled: true
