---
- hosts: localhost
  gather_facts: false
  vars_files:
    - secrets.yml
  tasks:
    - name: Generar docker-compose con variables
      template:
        src: docker-compose.yml.j2
        dest: ./docker-compose.generated.yml
