version: "3.8"

services:
  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    container_name: fastapi_app
    ports:
      - "8000:80"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
